apiVersion: v1
kind: Pod
metadata:
  name: test-correct-label
  namespace: team-alpha
  labels:
    team: alpha
spec:
  securityContext:
    runAsNonRoot: true
    runAsUser: 1000
    seccompProfile:
      type: RuntimeDefault
  containers:
    - name: test-correct-label
      image: busybox
      command: ["sleep", "3600"]
      securityContext:
        allowPrivilegeEscalation: false
        capabilities:
          drop: ["ALL"]
      resources:
        limits:
          cpu: "200m"
          memory: "128Mi"