apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: allow-dns
  namespace: team-alpha
spec:
  podSelector: {}
  policyTypes:
    - Egress
  egress:
    - to:
        - namespaceSelector:
            matchLabels: # AND filter
              kubernetes.io/metadata.name: kube-system # communication only to pod in the kube-system namespace
          podSelector:
            matchLabels:
              k8s-app: kube-dns # communication only to pod with label k8s-app=kube-dns
      ports: #communication with DNS server
        - protocol: UDP
          port: 53
        - protocol: TCP
          port: 53