apiVersion: v1
kind: Pod
metadata:
  name: test-quota-pod
  namespace: team-alpha
  labels:
    team: alpha
spec:
  securityContext:
    runAsNonRoot: true
    runAsUser: 1000
    seccompProfile:
      type: RuntimeDefault
  containers:
    - name: test-quota-pod
      image: busybox
      command: ["sleep", "3600"]
      securityContext:
        allowPrivilegeEscalation: false
        capabilities:
          drop: ["ALL"]
      resources:
        requests:
          cpu: "50m"
          memory: "64Mi"
        limits:
          cpu: "50m"
          memory: "64Mi"
#used in a for loop for testing the max number of pods that can be created in a namespace