apiVersion: v1
kind: LimitRange
metadata:
  name: team-alpha-limits
  namespace: team-alpha
spec:
  limits: # specifies the default and maximum compute resources that can be consumed by containers in the team-alpha namespace
    - type: Container
      defaultRequest:
        cpu: "100m"
        memory: 128Mi
      default:
        cpu: "250m"
        memory: 256Mi
      min:
        cpu: "50m"
        memory: 64Mi
      max:
        cpu: "500m"
        memory: 768Mi