apiVersion: v1
kind: LimitRange
metadata:
  name: team-beta-limits
  namespace: team-beta
spec:
  limits: # specifies the default and maximum compute resources that can be consumed by containers in the team-beta namespace
    - type: Container
      default:
        cpu: "250m"
        memory: 256Mi
      defaultRequest:
        cpu: "100m"
        memory: 128Mi
      max:
        cpu: "1"
        memory: 1Gi
      min:
        cpu: "50m"
        memory: 64Mi