apiVersion: v1
kind: ResourceQuota
metadata:
  name: team-alpha-quota
  namespace: team-alpha
spec:
  hard: # specifies the maximum amount of compute resources that can be consumed by the team-alpha namespace
    requests.cpu: "600m" #minimum amounto of CPU
    requests.memory: 1200Mi
    limits.cpu: "1200m" #maximum amount of CPU
    limits.memory: 2000Mi
    pods: "10"