apiVersion: v1
kind: ResourceQuota
metadata:
  name: team-beta-quota
  namespace: team-beta
spec:
  hard: # specifies the maximum amount of compute resources that can be consumed by the team-beta namespace
    requests.cpu: "400m" #minimum amounto of CPU
    requests.memory: 800Mi
    limits.cpu: "700m" #maximum amount of CPU
    limits.memory: 1400Mi
    pods: "10"