apiVersion: v1
kind: ResourceQuota
metadata:
  name: team-alpha-quota
  namespace: team-alpha
spec:
  hard: # specifies the maximum amount of compute resources that can be consumed by the team-alpha namespace
    requests.cpu: "600m" #minimum amounto of CPU
    requests.memory: 1200Mi
    limits.cpu: "900m" #maximum amount of CPU, less then 1 beacause some resources are for the system pod
    limits.memory: 2000Mi
    pods: "10"